name: Publish to Nuget

on:
  push:
    branches:
      - main
  
  # See also: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  publish:
    name: Build, pack and publish to Nuget
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Check-out Source

      # See also: https://github.com/actions/virtual-environments/issues/1891
      - uses: actions/setup-dotnet@v1 
        name: Setup dotnet
        with:
          dotnet-version: 5.0.x

      - name: Calculate Version
        shell: bash
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        run: |
          # Installs Minver-CLI
          dotnet tool install minver-cli --version 2.3.1

          # Gets the version number
          MINVER_VERSION=$(dotnet minver --auto-increment patch --tag-prefix v --verbosity t) 

      # See also: https://github.com/marketplace/actions/publish-nuget
      - uses: rohith/publish-nuget@v2
        name: Build and publish Nuget-Package 'TitanShark.Thresher.Core'
        with:
          PROJECT_FILE_PATH: TitanShark.Thresher.Core/TitanShark.Thresher.Core.csproj 
          PACKAGE_NAME: TitanShark.Thresher.Core
          VERSION_STATIC: ${{env.MINVER_VERSION}}
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_SOURCE: https://api.nuget.org
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: false