name: Publish to Nuget

on:
  push:
    branches:
      - main
  
  # See also: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  publish:
    name: Build, pack and publish to Nuget
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Check-out Source
        with:
          fetch-depth: 0

      # See also: https://github.com/actions/virtual-environments/issues/1891
      - uses: actions/setup-dotnet@v1 
        name: Setup DotNet CLI 5.0.x
        with:
          dotnet-version: 5.0.x

      - name: Build and Run Tests
        shell: bash
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        run: |
          dotnet build --configuration Release
          dotnet test ./**/bin/**/net*/*Tests.dll
      
      - name: Pack and Publish to Nuget
        shell: bash
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        run: |
          dotnet pack
          dotnet nuget push ./**/bin/**/*.nupkg --api-key $NUGET_KEY --source https://api.nuget.org/v3/index.json

      # See also: https://itnext.io/creating-a-github-action-to-tag-commits-2722f1560dec
      - name: Add Git-Tag corresponding Current SEMVER-Version
        shell: bash
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        run: |
          dotnet tool install -g minver-cli --version 2.3.1
          version=$(minver --auto-increment patch --tag-prefix v --verbosity t)
          commit=$(git rev-parse HEAD)
          # POST a new ref to repo via Github API
          curl -s -X POST $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/git/refs \
          -d @- << EOF
          {
            "ref": "refs/tags/$version",
            "sha": "$commit"
          }
          EOF

